/**
 * API client barrel — re-exports REST + WebSocket modules.
 * Existing `from '../api'` / `from '@/api'` / `from './api'` imports stay unchanged.
 */

export {
  setApiKey,
  initApiKeyFromStorage,
  getApiKey,
} from "./api/shared";

export {
  getSocket,
  streamChat,
  pushInsert,
  joinAgentChannel,
  leaveAgentChannel,
  subscribeAgentStream,
  subscribeAgentStatus,
  Channel,
} from "./api/ws";
export type { ChatEvent, ActivityEntry } from "./api/ws";

export {
  getProjects,
  activateProject,
  deactivateProject,
  createProject,
  updateProject,
  deleteProject,
  getProjectGameTime,
  getProjectGoals,
  updateProjectGoals,
  getOrgTree,
  getAgent,
  updateAgent,
  deleteAgent,
  getInbox,
  sendInboxMessage,
  getChatHistory,
  markMessagesRead,
  pauseSystem,
  resumeSystem,
  getPausedState,
  restartBackend,
  restartFrontend,
  getSettings,
  getSetting,
  upsertSetting,
  updateSettings,
  getMcpServers,
  addMcpServer,
  removeMcpServer,
  getMcpServerTools,
  getAgentMcp,
  bindAgentMcp,
  unbindAgentMcp,
  getLlmModels,
  getAgentTemplates,
  getHealth,
  getPendingApprovals,
  getProjectPendingApprovals,
  respondToApproval,
  getAgentPermissions,
  updateAgentPermissions,
  getPermissionRules,
  getChatMessages,
  getModels,
  createModel,
  updateModel,
  deleteModel,
  testModel,
  detectCapabilities,
  getProviderPresets,
  testModelConnection,
  getTierConfig,
  saveTierConfig,
  getImageGenConfig,
  saveImageGenConfig,
  getCommunications,
  sendCommunication,
  getUserPings,
  markPingRead,
  getProjectAlarms,
  scheduleAlarm,
  cancelAlarm,
  getAgentTodos,
  executeTodoWrite,
  getWorkLogs,
  getQuestions,
  answerQuestion,
  browseDirectory,
  pickFolderNative,
  getAgentTraces,
  getTaskTimeline,
  getTeamActivity,
  listTasks,
  getProjectTokenUsage,
  getProjectTokenDaily,
  getPlatformTokenUsage,
  tokenRequestTypeLabel,
  getAgentsLiveStatus,
  getActiveMeeting,
} from "./api/rest";

export type {
  AgentLiveStatus,
  AgentLivePhase,
  MeetingInfo,
} from "./api/rest";

export type {
  Project,
  KeyResult,
  GoalsData,
  WorkspaceCleanupResult,
  DeleteProjectResponse,
  PendingApproval,
  LlmModel,
  McpServer,
  McpServerUpsertInput,
  DetectedCapabilities,
  ProviderPreset,
  PresetModel,
  TestConnectionResult,
  ModelTier,
  TierConfig,
  ImageGenConfig,
  Communication,
  UserPing,
  ProjectAlarm,
  AgentTodos,
  WorkLog,
  PendingQuestion,
  BrowseResult,
  PickFolderNativeResult,
  TraceTurn,
  RawTraceMessage,
  TraceEvent,
  AgentTraces,
  TeamActivityQuery,
  TokenUsageEntry,
  TokenUsageSummary,
  TokenDailyEntry,
} from "./api/rest";
