/**
 * Flower-name (花名) generator.
 *
 * Generates 1–4 character Chinese names with diverse styles:
 *   - Poetic (诗意): single expressive character
 *   - Nature (自然): landscape/season imagery
 *   - Modern (现代): abstract, contemporary feel
 *   - Bold (豪放): powerful, martial, energetic
 *   - Elegant (典雅): refined, classical literati
 *   - Playful (随性): casual, whimsical, animal-themed
 *
 * HR can override these — this is the default auto-generation pool.
 */

// ---------------------------------------------------------------------------
// Name pools by style
// ---------------------------------------------------------------------------

const POETIC_SINGLE = [
  "寂", "默", "禅", "澈", "渡", "归", "隐", "逸",
  "止", "觉", "空", "宁", "静", "渊", "素", "简",
];

const NATURE_PAIRS = [
  "霜月", "暮雨", "柳烟", "云溪", "海雾", "露华", "霞光",
  "风荷", "星野", "雪霁", "松风", "鹤影", "蝉鸣", "萤火",
  "春涧", "秋潭", "朝露", "夕岚", "山月", "水镜",
];

const MODERN_SHORT = [
  "未央", "无邪", "半夏", "浮生", "初見", "长歌",
  "远行", "来迟", "不知", "可期", "如一", "重逢",
  "默存", "向晚", "拾光", "等风",
];

const BOLD_NAMES = [
  "剑心", "破阵", "凌霄", "斩风", "逆鳞", "惊鸿",
  "铁衣", "燃灯", "铸骨", "擎天", "踏雪", "逐日",
  "断浪", "劈山", "疾风", "雷动",
];

const ELEGANT_NAMES = [
  "寒露", "霜降", "白鹭", "紫烟", "青鸾", "碧落",
  "玄机", "灵犀", "锦瑟", "玉壶", "冰弦", "银烛",
  "瑶台", "琼枝", "画屏", "篆香",
];

const PLAYFUL_NAMES = [
  "猫九", "鱼丸", "豆包", "汤圆", "栗子", "年糕",
  "橘子", "红枣", "芝麻", "花生", "糖瓜", "肉松",
  "小满", "大寒", "端午", "重阳",
];

const THREE_CHAR_NAMES = [
  "风之子", "水中月", "镜中花", "云中鹤", "石上泉",
  "梦里身", "画外音", "局外人", "守夜人", "摆渡人",
  "半山居", "逍遥游", "无所有", "有所思",
];

const FOUR_CHAR_NAMES = [
  "一蓑烟雨", "长风万里", "大漠孤烟", "流星赶月",
  "白驹过隙", "高山流水", "来日方长", "春风得意",
  "浮云一别", "人间草木",
];

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/** All pools with their style tag. */
const POOLS: { style: string; names: string[] }[] = [
  { style: "poetic", names: POETIC_SINGLE },
  { style: "nature", names: NATURE_PAIRS },
  { style: "modern", names: MODERN_SHORT },
  { style: "bold", names: BOLD_NAMES },
  { style: "elegant", names: ELEGANT_NAMES },
  { style: "playful", names: PLAYFUL_NAMES },
  { style: "poetic-3", names: THREE_CHAR_NAMES },
  { style: "poetic-4", names: FOUR_CHAR_NAMES },
];

export function generateFlowerName(): { name: string; style: string } {
  const pool = POOLS[Math.floor(Math.random() * POOLS.length)]!;
  const name = pool.names[Math.floor(Math.random() * pool.names.length)]!;
  return { name, style: pool.style };
}

/** Check whether a name looks like it was generated by this system. */
export function isFlowerName(name: string): boolean {
  if (!name || name.length < 1 || name.length > 4) return false;
  for (const ch of name) {
    if (/[一-龥]/.test(ch)) continue; // Chinese char
    return false; // contains non-Chinese — probably a user-set display name
  }
  return true;
}

